apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: quay.io/phatthananvst01/nodejsimage:v1.0.0
        ports:
        - containerPort: 3000
